name: hbchat
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - langchain>=0.1.0
    - langchain-community>=0.0.13
    - langchain-openai>=0.0.5
    - faiss-cpu>=1.8.0
    - chromadb>=0.4.22
    - unstructured>=0.11.8
    - markdown>=3.5.1
    - openai>=1.7.2
    - tiktoken>=0.5.2
    - sentence-transformers>=2.2.2
    - gradio>=4.14.0
    - streamlit>=1.29.0
    - python-dotenv>=1.0.0

